services:
    web:
      build: .
      restart: always
      env_file:
        - .env
      restart: always
      env_file:
        - .env
  
    nginx:
      image: jonasal/nginx-certbot:latest
      restart: unless-stopped
      env_file:
        - ./nginx-certbot.env
      ports:
        - 80:80
        - 443:443
      volumes:
        - nginx_secrets:/etc/letsencrypt
        - ./user_conf.d:/etc/nginx/user_conf.d
      depends_on:
        - web
    
    database:
      # image to fetch from docker hub
      image: mysql/mysql-server:5.7

      # Environment variables for startup script
      # container will use these variables
      # to start the container with these define variables. 
      environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=testuser"
        - "MYSQL_PASSWORD=admin123"
        - "MYSQL_DATABASE=backend"
      # Mount init.sql file to automatically run 
      # and create tables for us.
      # everything in docker-entrypoint-initdb.d folder
      # is executed as soon as container is up nd running.
      volumes:
        - "/usercode/db/init.sql:/docker-entrypoint-initdb.d/init.sql"

  
volumes:
  nginx_secrets: